[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
target-version = "py311"

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.mypy]
python_version = "3.13"
disallow_untyped_defs = true
no_implicit_optional = true
warn_return_any = true
pretty = true
