Repository: marbatis/ai-dataset-health-zos
Mode: code
Branch: codex/understand-repo-purpose-and-goals   # the PR #9 branch

Task:
Fix CI on PR #9 by upgrading the artifact action.

Steps:
1) Edit .github/workflows/ci.yml
   - Change:
       uses: actions/upload-artifact@v3
     to:
       uses: actions/upload-artifact@v4
   - Do not change any other steps.

2) (Optional doc touch-up) In README’s “Run Tests” snippet, use:
     ruff check .
     black --check .
     pytest

3) Commit to the same branch and let CI re-run. Report the latest CI result.

Return:
- Files changed list
- Confirmation that CI is green on PR #9
- PR link