name: CI

on:
  pull_request:
  push:

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pytest

      - name: Lint with ruff
        run: ruff check . --output-format=github

      - name: Check formatting with black
        run: black --check .

      - name: Run tests
        if: ${{ hashFiles('tests/**/*.py') != '' }}
        run: pytest --junitxml=test-results.xml

      - name: Upload test results
        if: ${{ always() && hashFiles('tests/**/*.py') != '' }}
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: test-results.xml
