name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml
            requirements*.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pytest pytest-cov mypy

      - name: Lint with ruff
        run: ruff check . --output-format=github

      - name: Check formatting with black
        run: black --check .

      - name: Run mypy
        run: mypy .

      - name: Run tests (if present)
        if: ${{ hashFiles('tests/**/*.py') != '' }}
        env:
          PYTHONPATH: .
        run: |
          pytest -q --junitxml=test-results.xml --cov=./ --cov-report=term-missing --cov-fail-under=80

      - name: Upload pytest results
        if: ${{ always() && hashFiles('tests/**/*.py') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: test-results.xml
