name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml
            requirements*.txt

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black mypy pytest pytest-cov

      - name: Ruff check
        run: ruff check . --output-format=github

      - name: Black check
        run: black --check .

      - name: Mypy
        run: mypy .

      - name: Pytest (coverage ≥80)
        env:
          PYTHONPATH: .
        run: |
          pytest -q --junitxml=test-results.xml \
            --cov=./ --cov-report=term-missing --cov-fail-under=80

      - name: Health (smoke)
        env:
          PYTHONPATH: .
        run: |
          python list_files.py . --health | tee health.txt

      - name: Upload pytest results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: test-results.xml

      - name: Upload health results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: health-output
          path: health.txt
